In [1]:
import  numpy as np

x = np.arange(0, 4, 1)
x

array([0, 1, 2, 3])

In [3]:
np.mean(x)


1.5

In [4]:
np.std(x)

1.118033988749895

In [5]:
np.var(x)

1.25

In [6]:
np.sum(x)

6

In [7]:
np.prod(x)

0

In [8]:
a=np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [9]:
a[1,1]

1

In [10]:
b=np.arange(10)

In [11]:
b[2:9:3]

array([2, 5, 8])

In [12]:
np.array_equal(a,b)

False

In [13]:
a.min()

0

In [14]:
a.max()

2

In [15]:
c=a+1.5
c

array([[1.5, 1.5, 1.5],
       [1.5, 2.5, 1.5],
       [1.5, 1.5, 3.5]])

In [16]:
np.around(c)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 4.]])

In [19]:
d=np.arange(1,5)
d

array([1, 2, 3, 4])

In [21]:
e=d.flatten()
e

array([1, 2, 3, 4])

In [22]:
np.repeat(e, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [23]:
np.tile(e, 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [25]:
np.concatenate((d,e), axis=0)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [26]:
f=np.copy(e)
f

array([1, 2, 3, 4])