In [4]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matriz.shape

(2, 3)

In [7]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz2 = np.matrix(lista)
matriz2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
np.shape(matriz2)

(3, 3)

In [11]:
matriz2.size

9

In [14]:
matriz2.itemsize

8

In [15]:
matriz2.nbytes

72

In [17]:
matriz2[2,1]=9

In [18]:
matriz2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 9, 9]])

In [19]:
np.array([1,2], dtype=np.float64)

array([1., 2.])

In [21]:
matriz2.ndim

2